CREATE TABLE restaurant_order (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number   INTEGER,
    table_id       BIGINT       NOT NULL REFERENCES restaurant_table (id),
    status         VARCHAR(20)  NOT NULL,
    placed_at      TIMESTAMPTZ,
    payment_method VARCHAR(20)
);

CREATE TABLE order_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL REFERENCES restaurant_order (id),
    name       VARCHAR(255)   NOT NULL,
    size       VARCHAR(255)   NOT NULL,
    quantity   INTEGER        NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    note       TEXT
);

CREATE TABLE order_status_history (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT      NOT NULL REFERENCES restaurant_order (id),
    status           VARCHAR(20) NOT NULL,
    changed_at       TIMESTAMPTZ NOT NULL,
    staff_account_id BIGINT      REFERENCES staff_account (id)
);
