-- The number guests, the kitchen, the hall board and the admin screens show. order_number stays the internal,
-- always-unique number (and its unique index) and is never reset; display_number restarts at 1 when an admin resets
-- the series. Existing orders keep the number they were shown, and the series continues where it was.
ALTER TABLE restaurant_order ADD COLUMN display_number INTEGER;
UPDATE restaurant_order SET display_number = order_number;

ALTER TABLE order_number_counter ADD COLUMN next_display_value INTEGER;
UPDATE order_number_counter SET next_display_value = next_value;
ALTER TABLE order_number_counter ALTER COLUMN next_display_value SET NOT NULL;

-- The audit history search by number looks up the displayed number.
CREATE INDEX restaurant_order_display_number ON restaurant_order (display_number);

-- Every reset: who did it, when, and where the series stood (the number the next order would have got).
CREATE TABLE order_number_reset (
    id                     BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reset_at               TIMESTAMPTZ NOT NULL,
    staff_account_id       BIGINT      NOT NULL REFERENCES staff_account (id),
    previous_next_display  INTEGER     NOT NULL
);
