CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INTEGER NOT NULL
);

CREATE TABLE category_translation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT      NOT NULL REFERENCES category (id),
    language    VARCHAR(2)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    CONSTRAINT uk_category_translation_category_language UNIQUE (category_id, language)
);
