CREATE TABLE meal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT  NOT NULL REFERENCES category (id),
    available   BOOLEAN NOT NULL
);

CREATE TABLE meal_translation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id             BIGINT       NOT NULL REFERENCES meal (id),
    language            VARCHAR(2)   NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         TEXT,
    preparation_method  TEXT,
    CONSTRAINT uk_meal_translation_meal_language UNIQUE (meal_id, language)
);

CREATE TABLE meal_translation_ingredient (
    meal_translation_id BIGINT       NOT NULL REFERENCES meal_translation (id),
    position             INTEGER      NOT NULL,
    ingredient            VARCHAR(255) NOT NULL,
    PRIMARY KEY (meal_translation_id, position)
);

CREATE TABLE meal_size (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id BIGINT       NOT NULL REFERENCES meal (id),
    label   VARCHAR(255) NOT NULL,
    price   NUMERIC(10, 2) NOT NULL
);
