CREATE TABLE raw_material (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    unit              VARCHAR(50)  NOT NULL,
    in_stock_quantity NUMERIC(10, 2),
    supplier          VARCHAR(255)
);
