CREATE TABLE recipe (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_size_id     BIGINT NOT NULL REFERENCES meal_size (id),
    raw_material_id  BIGINT NOT NULL REFERENCES raw_material (id),
    quantity         NUMERIC(10, 2) NOT NULL,
    CONSTRAINT uk_recipe_meal_size_raw_material UNIQUE (meal_size_id, raw_material_id)
);
