ALTER TABLE meal_size DROP COLUMN label;

CREATE TABLE meal_size_translation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_size_id BIGINT       NOT NULL REFERENCES meal_size (id),
    language     VARCHAR(2)   NOT NULL,
    label        VARCHAR(255) NOT NULL,
    CONSTRAINT uk_meal_size_translation_meal_size_language UNIQUE (meal_size_id, language)
);
