CREATE TABLE restaurant_table (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number     VARCHAR(255) NOT NULL,
    room             VARCHAR(255) NOT NULL,
    seats            INTEGER      NOT NULL,
    paired_device_id VARCHAR(255),
    last_seen_at     TIMESTAMPTZ,
    CONSTRAINT uk_restaurant_table_table_number UNIQUE (table_number)
);
