CREATE TABLE staff_account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    pin_hash      VARCHAR(255),
    last_seen_at  TIMESTAMPTZ
);
