CREATE TABLE config (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code    VARCHAR(3)     NOT NULL,
    currency_symbol  VARCHAR(10)    NOT NULL,
    symbol_position  VARCHAR(10)    NOT NULL,
    tax_rate         NUMERIC(10, 2) NOT NULL,
    default_language VARCHAR(2)     NOT NULL
);

CREATE TABLE config_payment_method (
    config_id      BIGINT      NOT NULL REFERENCES config (id),
    payment_method VARCHAR(20) NOT NULL,
    PRIMARY KEY (config_id, payment_method)
);

INSERT INTO config (currency_code, currency_symbol, symbol_position, tax_rate, default_language)
VALUES ('EUR', '€', 'SUFFIX', 19.00, 'DE');

INSERT INTO config_payment_method (config_id, payment_method)
VALUES (1, 'CASH'),
       (1, 'CARD'),
       (1, 'PAYPAL'),
       (1, 'CASH_DESK');
